### ISSUE TITLE
Fatal errors while determining PSF in u band Run1.2i images

### ISSUE THREAD

**Issue by boutigny** [LSSTDESC/DC2-production#307]
@johannct and I have seen several errors in `singleFrameDriver` related to PSF determination in `u` band Run1.2i images.
In the `uDDF-u` we get:
* 271 `FATAL` error messages from 18 visits
* The list of faulty visits is [ 1237924,  1409594, 1438328, 1452552, 1472759, 1682212, 1683076, 1683675, 1924614, 256304, 256981, 675910, 699418, 700187, 723095, 738955, 966044, 997997]
* Visits 699418 and 738955 have all their CCD failing

There 2 types of error messages:
```singleFrameDriver: Failed on dataId={'visit': 738955, 'run': '738955', 'raftName': 'R01', 'detectorName': 'S12', 'detector': 5, 'snap': 0}: RuntimeError: No objects passed our cuts for consideration as psf stars```

and

```singleFrameDriver: Failed on dataId={'visit': 738955, 'run': '738955', 'raftName': 'R01', 'detectorName': 'S02', 'detector': 2, 'snap': 0}: InvalidParameterError: 
  File "src/PsfexPsf.cc", line 235, in virtual std::shared_ptr<lsst::afw::image::Image<double> > lsst::meas::extensions::psfex::PsfexPsf::_doComputeImage(const Point2D&, const lsst::afw::image::Color&, const Point2D&) const
    Only spatial variation (ndim == 2) is supported; saw 0 {0}
lsst::pex::exceptions::InvalidParameterError: 'Only spatial variation (ndim == 2) is supported; saw 0'
```
 All this is with `obs_lsstCam -b w.2018.39-run1.2` and with release `w_2018_39`

**Comment by heather999** [comment]
The processing using the same versions of the stack and obs_lsst at NERSC similarly sees these errors.  I'd also note that the SIP order setting seems to have no impact on this, as I see these errors even before we made that config change.  There are some warnings and a traceback in the case of the `No objects passed our cuts` error:
```47304 INFO  2018-11-28T17:30:17.503-0800 singleFrameDriver: nid00784:47304: Finished processing {'visit': 699418, 'run': '699418', 'raftName': 'R01', 'detectorName': 'S20', 'detector': 6, 'snap': 0}                                                      
47307 INFO  2018-11-28T17:30:17.535-0800 singleFrameDriver.processCcd.charImage.measurePsf: Measuring PSF                     
47299 INFO  2018-11-28T17:30:18.176-0800 CameraMapper: Loading calib registry from /global/cscratch1/sd/desc/DC2/ALCF_Run1.2i/newcalibration/w_2018_39/CALIB/calibRegistry.sqlite3                                                                          

> WARNING: 1st context group-degree lowered (not enough samples)

> WARNING: 1st context group removed (not enough samples)

47308 INFO  2018-11-28T17:30:18.414-0800 singleFrameDriver.processCcd.charImage.measurePsf: PSF determination using 1/1 stars.
Traceback (most recent call last):                                                                                            
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-12-g726f8f3+6/python/lsst/pipe/base/cmdLineTask.py", line 388, in __call__                                                              
    result = self.runTask(task, dataRef, kwargs)                                                                              
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-12-g726f8f3+6/python/lsst/pipe/base/cmdLineTask.py", line 447, in runTask                                                               
    return task.runDataRef(dataRef, **kwargs)                                                                                 
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_drivers/16.0-6-gf9cb114+9/python/lsst/pipe/drivers/singleFrameDriver.py", line 72, in runDataRef                                                  
    return self.processCcd.runDataRef(sensorRef)                                                                              
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-12-g726f8f3+6/python/lsst/pipe/base/timer.py", line 149, in wrapper                                                                     
    res = func(self, *args, **keyArgs)                                                                                        
  File "/global/cscratch1/sd/desc/DC2/ALCF_Run1.2i/newcalibration/software/pipe_tasks/python/lsst/pipe/tasks/processCcd.py", line 188, in runDataRef                                                                                                        
    doUnpersist=False,                                                                                                        
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-12-g726f8f3+6/python/lsst/pipe/base/timer.py", line 149, in wrapper                                                                     
    res = func(self, *args, **keyArgs)                                                                                        
  File "/global/cscratch1/sd/desc/DC2/ALCF_Run1.2i/newcalibration/software/pipe_tasks/python/lsst/pipe/tasks/characterizeImage.py", line 349, in runDataRef                                                                                                 
    background=background,                                                                                                    
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-12-g726f8f3+6/python/lsst/pipe/base/timer.py", line 149, in wrapper                                                                     
    res = func(self, *args, **keyArgs)                                                                                        
  File "/global/cscratch1/sd/desc/DC2/ALCF_Run1.2i/newcalibration/software/pipe_tasks/python/lsst/pipe/tasks/characterizeImage.py", line 407, in run                                                                                                        
    background=background,                                                                                                    
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-12-g726f8f3+6/python/lsst/pipe/base/timer.py", line 149, in wrapper                                                                     
    res = func(self, *args, **keyArgs)                                                                                        
  File "/global/cscratch1/sd/desc/DC2/ALCF_Run1.2i/newcalibration/software/pipe_tasks/python/lsst/pipe/tasks/characterizeImage.py", line 501, in detectMeasureAndEstimatePsf                                                                                
    expId=exposureIdInfo.expId)                                                                                               
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-12-g726f8f
3+6/python/lsst/pipe/base/timer.py", line 149, in wrapper                                                                     
    res = func(self, *args, **keyArgs)                                                                                        
  File "/global/cscratch1/sd/desc/DC2/ALCF_Run1.2i/newcalibration/software/pipe_tasks/python/lsst/pipe/tasks/measurePsf.py", line 274, in run                                                                                                               
    stars = self.starSelector.run(sourceCat=sources, matches=matches, exposure=exposure)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/meas_algorithms/16.0-17-g
6a7bfb3b+8/python/lsst/meas/algorithms/sourceSelector.py", line 110, in run
    matches=matches)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/meas_algorithms/16.0-17-g
6a7bfb3b+8/python/lsst/meas/algorithms/objectSizeStarSelector.py", line 423, in selectSources
    raise RuntimeError("No objects passed our cuts for consideration as psf stars")
RuntimeError: No objects passed our cuts for consideration as psf stars
47315 INFO  2018-11-28T17:30:18.560-0800 singleFrameDriver.processCcd.charImage.measurePsf: Measuring PSF
47300 INFO  2018-11-28T17:30:18.633-0800 singleFrameDriver.processCcd.charImage.measurePsf: Measuring PSF

> WARNING: 1st context group-degree lowered (not enough samples)

> WARNING: 1st context group removed (not enough samples)

47306 INFO  2018-11-28T17:30:18.667-0800 singleFrameDriver.processCcd.charImage.measurePsf: PSF determination using 1/1 stars.
47314 INFO  2018-11-28T17:30:18.714-0800 singleFrameDriver.processCcd.charImage.measurePsf: Measuring PSF
47312 INFO  2018-11-28T17:30:18.807-0800 CameraMapper: Loading exposure registry from /global/cscratch1/sd/desc/DC2/ALCF_Run1.2i/newcalibration/w_2018_39/registry.sqlite3
47316 INFO  2018-11-28T17:30:19.004-0800 singleFrameDriver: nid00784:47316: Finished processing {'visit': 699418, 'run': '699418', 'raftName': 'R03', 'detectorName': 'S00', 'detector': 18, 'snap': 0}
47310 INFO  2018-11-28T17:30:19.010-0800 singleFrameDriver.processCcd.charImage.measurePsf: Measuring PSF
47302 INFO  2018-11-28T17:30:19.199-0800 CameraMapper: Loading calib registry from /global/cscratch1/sd/desc/DC2/ALCF_Run1.2i/newcalibration/w_2018_39/CALIB/calibRegistry.sqlite3
47301 INFO  2018-11-28T17:30:19.379-0800 singleFrameDriver.processCcd.charImage.measurePsf: Measuring PSF
47311 INFO  2018-11-28T17:30:19.827-0800 singleFrameDriver: nid00784:47311: Finished processing {'visit': 699418, 'run': '699418', 'raftName': 'R02', 'detectorName': 'S11', 'detector': 13, 'snap': 0}
47309 INFO  2018-11-28T17:30:19.978-0800 singleFrameDriver.processCcd.charImage.measurePsf: Measuring PSF

> WARNING: 1st context group-degree lowered (not enough samples)

> WARNING: 1st context group removed (not enough samples)

47313 INFO  2018-11-28T17:30:20.129-0800 singleFrameDriver.processCcd.charImage.measurePsf: PSF determination using 1/1 stars.
47298 INFO  2018-11-28T17:30:20.472-0800 singleFrameDriver.processCcd.charImage.measurePsf: Measuring PSF
47304 FATAL 2018-11-28T17:30:20.552-0800 singleFrameDriver: Failed on dataId={'visit': 699418, 'run': '699418', 'raftName': 'R01', 'detectorName': 'S20', 'detector': 6, 'snap': 0}: RuntimeError: No objects passed our cuts for consideration as psf stars
47307 INFO  2018-11-28T17:30:20.927-0800 singleFrameDriver.processCcd.charImage.measurePsf: PSF star selector found 1 candidates
```

**Comment by RobertLuptonTheGood** [comment]
It's telling you that there are no PSF stars.  If you put one of the visits that fails -- a single CCD would suffice -- in a place I can see them I can take a look.  It'd be easier if you had the calibrations, but I could work around that.   

I'm going to be in Shanghai next week, so won't be able to help remotely.

**Comment by RobertLuptonTheGood** [comment]
Also, it's *much* easier for me for this to appear in Jira.  That way we can promote it to a DM problem if/when appropriate

**Comment by heather999** [comment]
I transferred the data for the two u band uDDF visits where all the sensors failed ( 699418 and 738955) along with the CALIB directory to lsst-dev.  See `/project/shared/data/desc_dc2/github_307/w_2018_39`  Just let me know if anything is missing.

**Comment by johannct** [comment]
@RobertLuptonTheGood  Thanks to Lauren McArthur this is now captured in JIRA : https://jira.lsstcorp.org/browse/DM-16785

**Comment by katrinheitmann** [comment]
@boutigny Hi Dominique, has this problem been resolved? There is no traffic here for a few months. If it has been resolved, could you please provide a brief summary and close the issue? If not, what are the next steps to be taken? Thanks!

**Comment by boutigny** [comment]
I have lost track of what happened with this issue. I guess that it has been solved but I think that @johannct or @rearmstr will know better than me.

**Comment by johannct** [comment]
The singleframedriver task has a dedicated config for u band, that does not check psf. The root issue has not been solved, but this is not a problem for DC anymore. The jira is open but I am not sure about actions taken on that side.

**Comment by boutigny** [comment]
The corresponding JIRA ticket is marked "done". It is difficult for me to understand whether we just put the problem "under the carpet" or if we really do not care in DC2 ?

**Comment by johannct** [comment]
Ok my comment about dc2 was based on not knowing that the jira was marked down. If a solution has been found, we definitely should propagate it down. Can someone track a weekly including it?

**Comment by boutigny** [comment]
Unfortunately, it is marked as done because the investigation has been completed, not because it is solved.

**Comment by heather999** [comment]
and I believe from the discussion in the JIRA, there were no config modifications ultimately suggested.
Just to clarify, is it singleFrameDriver or coaddDriver that has the dedicated config for the u band? The config I am aware of is: https://github.com/lsst/obs_lsst/blob/master/config/coaddDriver_noPSF.py
My understanding is that we intend to use this going forward as well for the Run2.1i processing.

**Comment by jchiang87** [comment]
I think this is it: https://github.com/LSSTDESC/ImageProcessingPipelines/blob/master/workflows/srs/dm_configs/processCcdConfig_u.py

Based on the discussion at the JIRA issue, there are a couple of config changes that we may want to consider, especially `charImage.measureApCorr.sourceSelector["objectSize"].fluxMin`, but I don't think we can settle on precise values until we try processing with the B/F correction enabled.

**Comment by rearmstr** [comment]
I think the default setting for "objectSize".fluxMin is fairly arbitrary at this point.  I think lowering it would be a good idea as it helps where there are few stars on a chip, but I don't think it is critical for most cases.  When I looked at this before it slightly increased the number stars for PSF modeling, but didn't make a big difference for most ccds.  

I think the initial problem was with the seeing of the input images, right?  Maybe this should be closed and a new issue opened if we want to reduce the minimum flux?

**Comment by heather999** [comment]
I need @johannct to confirm.. but I see where `coaddDriver_noPSF.py` [is used directly in the SRS workflow](https://github.com/LSSTDESC/ImageProcessingPipelines/blob/dc2/run2.1/workflows/srs/pipe_scripts/build_coaddDriver_scripts_fromdb.py), but that `processCcdConfig_u.py` does not appear in the SingleFrameDriver set up.. and that particular config file is a year old and was introduced by Nicolas.. It is probably outdated in any case.
We have discussed this before, but we need to clean up (or clear out) `workflows/srs/dm_configs` and move everything that is still pertinent to `ImageProcessingPipelines/configs` I'll make an issue :)

**Comment by johannct** [comment]
yes ciadddriver, sorry

**Comment by johannct** [comment]
we should be closing this, as there are PSF failure isses to be dealt with for 2.1i.
